const root=document.querySelector("#game"),boot=document.querySelector("#boot"),hooks=new Map(),menus=new Map();
const NativeAudio=window.AudioContext||window.webkitAudioContext,contexts=new Set();
if(NativeAudio){const Audio=window.AudioContext=function(...a){const c=new NativeAudio(...a);contexts.add(c);return c};Audio.prototype=NativeAudio.prototype;window.webkitAudioContext=Audio;document.addEventListener("pointerdown",()=>contexts.forEach(c=>c.state==="suspended"&&c.resume().catch(()=>{})),{capture:true})}
const GDML=window.GDML={version:"1.3.0",root,loaded:[],hooks,assets:null,menu:{register(name,api={}){menus.set(name,api);GDML.emit("menuRegister",name,api);return()=>menus.delete(name)},get:name=>menus.get(name),open(name,...args){GDML.emit("menuOpen",name,...args);menus.get(name)?.onOpen?.(...args)},close(name,...args){GDML.emit("menuClose",name,...args);menus.get(name)?.onClose?.(...args)},list:()=>[...menus.keys()]},on(t,f){let a=hooks.get(t);if(!a)hooks.set(t,a=[]);a.push(f);return()=>{let i=a.indexOf(f);if(i>=0)a.splice(i,1)}},emit(t,...a){for(const f of hooks.get(t)||[])try{f(...a)}catch(e){console.error("[GDML] hook",t,e)}}};
window.GDMLHook=(type,...args)=>GDML.emit(type,...args);
const nativeFetch=window.fetch,nativeOpen=XMLHttpRequest.prototype.open;
function assetURL(u){try{const x=new URL(u,location.href),file=decodeURIComponent(x.pathname.split("/").pop());if(!x.pathname.includes("/assets/")||!GDML.assets?.files[file])return u;return GDML.assets.base+GDML.assets.files[file]}catch{return u}}
XMLHttpRequest.prototype.open=function(m,u,...a){return nativeOpen.call(this,m,assetURL(u),...a)};
window.fetch=(input,...a)=>{if(typeof input==="string")input=assetURL(input);else if(input?.url)input=new Request(assetURL(input.url),input);return nativeFetch(input,...a)};
async function load(p){try{const m=await import("./mods/"+p);await(m.default||m.install)?.(GDML);GDML.loaded.push(p);GDML.emit("modLoaded",p)}catch(e){console.error("[GDML] "+p,e);GDML.emit("modError",p,e)}}
async function start(){if(GDML.started)return;GDML.started=true;boot?.remove();try{GDML.assets=await(await nativeFetch("./asset-map.json?"+Date.now(),{cache:"no-store"})).json()}catch(e){console.warn("[GDML] Asset map unavailable",e);GDML.assets={base:"https://web-dashers.github.io/assets/",files:{}}}for(const p of GDML.modList||[])if(typeof p==="string"&&p.endsWith(".js"))await load(p);GDML.emit("beforeGame");await import("./game.js?"+Date.now());GDML.emit("gameReady")}
(async()=>{try{GDML.modList=await(await nativeFetch("./mods.json?"+Date.now(),{cache:"no-store"})).json()}catch{GDML.modList=[]}document.addEventListener("pointerdown",start,{once:true,capture:true});document.addEventListener("keydown",start,{once:true,capture:true});GDML.emit("ready")})();
