import {installUI} from "./ui.js";

const root=document.querySelector("#game"),boot=document.querySelector("#boot"),hooks=new Map(),menus=new Map();
const NativeAudio=window.AudioContext||window.webkitAudioContext,contexts=new Set();let audioUnlocked=false;
if(NativeAudio){const Audio=window.AudioContext=function(...a){const c=new NativeAudio(...a);contexts.add(c);const resume=c.resume.bind(c);c.resume=()=>audioUnlocked?resume():Promise.resolve();return c};Audio.prototype=NativeAudio.prototype;window.webkitAudioContext=Audio;const unlockAudio=()=>{audioUnlocked=true;contexts.forEach(c=>c.state==="suspended"&&c.resume().catch(()=>{}))};document.addEventListener("pointerdown",unlockAudio,{capture:true,once:true});document.addEventListener("keydown",unlockAudio,{capture:true,once:true})}
const GDML=window.GDML={version:"2.0.0",root,loaded:[],hooks,assets:null,menu:{register(name,api={}){menus.set(name,api);GDML.emit("menuRegister",name,api);return()=>menus.delete(name)},get:name=>menus.get(name),open(name,...args){GDML.emit("menuOpen",name,...args);menus.get(name)?.onOpen?.(...args)},close(name,...args){GDML.emit("menuClose",name,...args);menus.get(name)?.onClose?.(...args)},list:()=>[...menus.keys()]},on(t,f){let a=hooks.get(t);if(!a)hooks.set(t,a=[]);a.push(f);return()=>{let i=a.indexOf(f);if(i>=0)a.splice(i,1)}},emit(t,...a){for(const f of hooks.get(t)||[])try{f(...a)}catch(e){console.error("[GDML] hook",t,e)}}};
GDML.ui=installUI(GDML);
window.GDMLHook=(type,...args)=>GDML.emit(type,...args);
const nativeFetch=window.fetch,nativeOpen=XMLHttpRequest.prototype.open;
const audioFallback=new Map();
function audioURL(file){if(audioFallback.has(file))return audioFallback.get(file);const rate=22050,dur=file.endsWith(".mp3")?.08:.045,n=rate*dur|0,buf=new ArrayBuffer(44+n*2),v=new DataView(buf);const w=(o,s)=>{for(let i=0;i<s.length;i++)v.setUint8(o+i,s.charCodeAt(i))};w(0,"RIFF");v.setUint32(4,36+n*2,true);w(8,"WAVE");w(12,"fmt ");v.setUint32(16,16,true);v.setUint16(20,1,true);v.setUint16(22,1,true);v.setUint32(24,rate,true);v.setUint32(28,rate*2,true);v.setUint16(32,2,true);v.setUint16(34,16,true);w(36,"data");v.setUint32(40,n*2,true);for(let i=0;i<n;i++){const t=i/rate,env=Math.max(0,1-t/dur),f=440+(file.length%7)*70;v.setInt16(44+i*2,Math.sin(t*f*6.28318)*env*.12*32767,true)}const url=URL.createObjectURL(new Blob([buf],{type:"audio/wav"}));audioFallback.set(file,url);return url}
function assetURL(u){try{const x=new URL(u,location.href),file=decodeURIComponent(x.pathname.split("/").pop().split("?")[0]);const map=GDML.assets||{};const local=map.local?.[file];let remote=map.files?.[file];if(local)return new URL("./assets/"+local,location.href).href;if(!remote){if(/^(bigFont|goldFont)\.(png|fnt)$/i.test(file))remote="assets/fonts/"+file;else if(/^GJ_.*Sheet.*\.(png|json)$/i.test(file)||/^(CCControlColourPickerSpriteSheet-uhd|FireSheet_01-hd|PixelSheet_01|Wavesheet|player_ball_00|player_dart_00|Robot_AnimDesc|Spider_AnimDesc)\.(png|json)$/i.test(file))remote="assets/sheets/"+file;else if(/^\d+\.txt$/i.test(file))remote="assets/levels/"+file;else if(/\.mp3$/i.test(file))remote="assets/music/"+file;else if(/\.(ogg|wav)$/i.test(file))remote="assets/sfx/"+file;else if(/^game_bg_\d+_001\.png$/i.test(file)||/^(GJ_button_|GJ_square|GJ_move|slider|square|gravityLine|loadingCircle|macro|playback|record|stop|tab|tutorial|export|import)\w*\.png$/i.test(file))remote="assets/sprites/"+file;}if(remote)return new URL(remote,map.base||"https://web-dashers.github.io/").href;return u}catch{return u}}
XMLHttpRequest.prototype.open=function(m,u,...a){return nativeOpen.call(this,m,assetURL(u),...a)};
window.fetch=(input,...a)=>{if(typeof input==="string")input=assetURL(input);else if(input?.url)input=new Request(assetURL(input.url),input);return nativeFetch(input,...a)};
for(const C of [window.HTMLImageElement,window.HTMLMediaElement])if(C){const d=Object.getOwnPropertyDescriptor(C.prototype,"src");if(d?.set)Object.defineProperty(C.prototype,"src",{...d,set(v){d.set.call(this,assetURL(v))}})}
async function load(p){try{const m=await import("../mods/"+p);await(m.default||m.install)?.(GDML);GDML.loaded.push(p);GDML.emit("modLoaded",p)}catch(e){console.error("[GDML] "+p,e);GDML.emit("modError",p,e)}}
async function start(){if(GDML.started)return;audioUnlocked=true;GDML.started=true;boot?.remove();try{GDML.assets=await(await nativeFetch("../config/asset-map.json?"+Date.now(),{cache:"no-store"})).json()}catch(e){console.warn("[GDML] Asset map unavailable",e);GDML.assets={base:"https://web-dashers.github.io/assets/",files:{}}}for(const p of GDML.modList||[])if(typeof p==="string"&&p.endsWith(".js"))await load(p);GDML.emit("beforeGame");await import("./game.js?"+Date.now());GDML.emit("gameReady")}
(async()=>{try{GDML.modList=await(await nativeFetch("../config/mods.json?"+Date.now(),{cache:"no-store"})).json()}catch{GDML.modList=[]}document.addEventListener("pointerdown",start,{once:true,capture:true});document.addEventListener("keydown",start,{once:true,capture:true});GDML.emit("ready")})();