export function installUI(GDML){
  let opened=false,positionOpen=false;
  GDML.position={x:0,y:0,size:1};
  const root=document.createElement("div");
  root.id="gdml-ui";
  root.innerHTML=`<button class="gdml-fab" type="button" aria-label="GdMLoader"><img src="./assets/local/branding/MLLogo.png" alt="GdMLoader"></button><button class="gdml-position-fab" type="button" aria-label="Положение игры">↕</button><div class="gdml-position-panel" aria-hidden="true"><div class="gdml-position-title">Положение игры</div><div class="gdml-position-grid"><button data-move="up">▲</button><button data-move="left">◀</button><button data-move="down">▼</button><button data-move="right">▶</button></div><div class="gdml-size-row"><span>Размер</span><button data-size="-1">−</button><b id="gdml-size">100%</b><button data-size="1">+</button></div><div class="gdml-position-readout">X: <b id="gdml-x">0</b> &nbsp; Y: <b id="gdml-y">0</b></div><button class="gdml-position-reset" type="button">Сбросить</button></div><div class="gdml-overlay" aria-hidden="true"><section class="gdml-panel" role="dialog" aria-label="GdMLoader"><header class="gdml-panel-head"><div class="gdml-brand"><img src="./assets/local/branding/MLLogo.png" alt=""><div><b>GdMLoader</b><small>Geometry Dash Web</small></div></div><button class="gdml-close" type="button" aria-label="Close">×</button></header><nav class="gdml-tabs"><button class="active" data-tab="mods">Mods</button><button data-tab="levels">Levels</button><button data-tab="about">About</button></nav><main><div class="gdml-page active" data-page="mods"><div class="gdml-card"><b>GdMLoader</b><p>Модификации загружаются до запуска игры.</p><span class="gdml-status">Загрузка...</span></div></div><div class="gdml-page" data-page="levels"><div class="gdml-card"><b>Levels</b><p>Уровни Geometry Dash.</p><span>Раздел готов для подключаемых уровней.</span></div></div><div class="gdml-page" data-page="about"><div class="gdml-card"><b>GdMLoader 2.0</b><p>Web Mod Loader для Geometry Dash.</p><span>F6 — открыть загрузчик</span></div></div></main></section></div>`;
  document.body.append(root);
  const fab=root.querySelector(".gdml-fab"),posFab=root.querySelector(".gdml-position-fab"),posPanel=root.querySelector(".gdml-position-panel"),overlay=root.querySelector(".gdml-overlay"),close=root.querySelector(".gdml-close"),xEl=root.querySelector("#gdml-x"),yEl=root.querySelector("#gdml-y"),sizeEl=root.querySelector("#gdml-size");
  const apply=()=>{GDML.layoutGame?.();xEl.textContent=GDML.position.x;yEl.textContent=GDML.position.y;sizeEl.textContent=Math.round(GDML.position.size*100)+"%"};
  const togglePosition=()=>{positionOpen=!positionOpen;root.classList.toggle("position-open",positionOpen);posPanel.setAttribute("aria-hidden",String(!positionOpen))};
  const setOpen=v=>{opened=v;root.classList.toggle("open",v);overlay.setAttribute("aria-hidden",String(!v));document.body.classList.toggle("gdml-modal-open",v);GDML.emit(v?"menuOpen":"menuClose","loader")};
  const open=()=>setOpen(true),closeMenu=()=>setOpen(false);
  fab.addEventListener("click",open);posFab.addEventListener("click",togglePosition);close.addEventListener("click",closeMenu);
  overlay.addEventListener("pointerdown",e=>{if(e.target===overlay)closeMenu()});
  root.querySelectorAll(".gdml-tabs button").forEach(b=>b.addEventListener("click",()=>{root.querySelectorAll(".gdml-tabs button").forEach(x=>x.classList.toggle("active",x===b));root.querySelectorAll(".gdml-page").forEach(x=>x.classList.toggle("active",x.dataset.page===b.dataset.tab))}));
  root.querySelectorAll("[data-move]").forEach(b=>b.addEventListener("click",()=>{const step=10;switch(b.dataset.move){case"up":GDML.position.y-=step;break;case"down":GDML.position.y+=step;break;case"left":GDML.position.x-=step;break;case"right":GDML.position.x+=step;break}apply()}));
  root.querySelectorAll("[data-size]").forEach(b=>b.addEventListener("click",()=>{GDML.position.size=Math.max(.25,Math.min(2,GDML.position.size+Number(b.dataset.size)*.05));apply()}));
  root.querySelector(".gdml-position-reset").addEventListener("click",()=>{GDML.position.x=0;GDML.position.y=0;GDML.position.size=1;apply()});
  window.addEventListener("keydown",e=>{if(e.key==="F6"){e.preventDefault();opened?closeMenu():open()}if(e.key==="Escape"){if(positionOpen)togglePosition();else if(opened)closeMenu()}});
  GDML.on("gameReady",()=>{root.classList.add("ready");const s=root.querySelector(".gdml-status");if(s)s.textContent=GDML.loaded.length?GDML.loaded.length+" mod(s) loaded":"No mods loaded"});
  GDML.ui={open,close:closeMenu,toggle:()=>setOpen(!opened),isOpen:()=>opened,state:{}};
  return GDML.ui;
}