export function installUI(GDML){
  let opened=false,dragging=false,dragX=0,dragY=0,startLeft=0,startTop=0;
  const root=document.createElement("div");
  root.id="gdml-ui";
  root.innerHTML=`<button class="gdml-fab" type="button" aria-label="GdMLoader"><img src="./assets/local/branding/MLLogo.png" alt="GdMLoader"></button><div class="gdml-overlay" aria-hidden="true"><section class="gdml-panel" role="dialog" aria-label="GdMLoader"><header class="gdml-panel-head"><div class="gdml-brand"><img src="./assets/local/branding/MLLogo.png" alt=""><div><b>GdMLoader</b><small>Geometry Dash Web</small></div></div><button class="gdml-close" type="button" aria-label="Close">×</button></header><nav class="gdml-tabs"><button class="active" data-tab="mods">Mods</button><button data-tab="position">Position</button><button data-tab="about">About</button></nav><main><div class="gdml-page active" data-page="mods"><div class="gdml-card"><b>GdMLoader</b><p>Модификации загружаются до запуска игры.</p><span class="gdml-status">Загрузка...</span></div></div><div class="gdml-page" data-page="position"><div class="gdml-card"><b>Положение игры</b><p>Включи настройку и перетаскивай окно Geometry Dash мышью.</p><button class="gdml-btn" id="gdml-position-toggle">Включить перетаскивание</button><div class="gdml-position-values">X: <b id="gdml-x">0</b> &nbsp; Y: <b id="gdml-y">0</b></div><button class="gdml-btn" id="gdml-copy-position">Скопировать X/Y</button><button class="gdml-btn" id="gdml-reset-position">Вернуть центр</button><p class="gdml-muted">После настройки пришли мне X и Y. Я зафиксирую их в игре и уберу этот режим.</p></div></div><div class="gdml-page" data-page="about"><div class="gdml-card"><b>GdMLoader 2.0</b><p>Web Mod Loader для Geometry Dash.</p><span>F6 — открыть загрузчик</span></div></div></main></section></div>`;
  document.body.append(root);
  const fab=root.querySelector(".gdml-fab"),overlay=root.querySelector(".gdml-overlay"),close=root.querySelector(".gdml-close"),canvas=()=>window.Phaser?.GAMES?.[0]?.canvas||GDML.root;
  const posEl=root.querySelector("#gdml-position-toggle"),xEl=root.querySelector("#gdml-x"),yEl=root.querySelector("#gdml-y");
  const updatePos=()=>{const c=canvas(),r=c.getBoundingClientRect();xEl.textContent=Math.round(r.left);yEl.textContent=Math.round(r.top)};
  const setManual=(on)=>{GDML.manualPosition=on;if(on){const c=canvas(),r=c.getBoundingClientRect();c.style.setProperty("transform","none","important");c.style.setProperty("left",Math.round(r.left)+"px","important");c.style.setProperty("top",Math.round(r.top)+"px","important");c.style.setProperty("margin","0","important");posEl.textContent="Выключить перетаскивание"}else{posEl.textContent="Включить перетаскивание";GDML.layoutGame?.();}updatePos()};
  const beginDrag=e=>{if(!GDML.manualPosition||e.button!==0)return;const c=canvas();dragging=true;dragX=e.clientX;dragY=e.clientY;const r=c.getBoundingClientRect();startLeft=r.left;startTop=r.top;e.preventDefault()};
  const moveDrag=e=>{if(!dragging)return;const c=canvas();const x=Math.round(startLeft+e.clientX-dragX),y=Math.round(startTop+e.clientY-dragY);c.style.setProperty("left",x+"px","important");c.style.setProperty("top",y+"px","important");c.style.setProperty("transform","none","important");updatePos()};
  const endDrag=()=>{dragging=false};
  document.addEventListener("pointerdown",beginDrag,true);document.addEventListener("pointermove",moveDrag,true);document.addEventListener("pointerup",endDrag,true);
  const setOpen=v=>{opened=v;root.classList.toggle("open",v);overlay.setAttribute("aria-hidden",String(!v));document.body.classList.toggle("gdml-modal-open",v);GDML.emit(v?"menuOpen":"menuClose","loader")};
  const open=()=>setOpen(true),closeMenu=()=>setOpen(false);
  fab.addEventListener("click",open);close.addEventListener("click",closeMenu);overlay.addEventListener("pointerdown",e=>{if(e.target===overlay)closeMenu()});
  root.querySelectorAll(".gdml-tabs button").forEach(b=>b.addEventListener("click",()=>{root.querySelectorAll(".gdml-tabs button").forEach(x=>x.classList.toggle("active",x===b));root.querySelectorAll(".gdml-page").forEach(x=>x.classList.toggle("active",x.dataset.page===b.dataset.tab));if(b.dataset.tab==="position")updatePos()}));
  posEl.addEventListener("click",()=>setManual(!GDML.manualPosition));
  root.querySelector("#gdml-copy-position").addEventListener("click",async()=>{updatePos();const t=`X: ${xEl.textContent}, Y: ${yEl.textContent}`;try{await navigator.clipboard.writeText(t)}catch{}root.querySelector("#gdml-copy-position").textContent="Скопировано: "+t;setTimeout(()=>root.querySelector("#gdml-copy-position").textContent="Скопировать X/Y",1200)});
  root.querySelector("#gdml-reset-position").addEventListener("click",()=>{GDML.manualPosition=false;GDML.layoutGame?.();updatePos();posEl.textContent="Включить перетаскивание"});
  window.addEventListener("keydown",e=>{if(e.key==="F6"){e.preventDefault();opened?closeMenu():open()}if(e.key==="Escape"&&opened)closeMenu()});
  GDML.on("gameReady",()=>{root.classList.add("ready");const s=root.querySelector(".gdml-status");if(s)s.textContent=GDML.loaded.length?GDML.loaded.length+" mod(s) loaded":"No mods loaded";setTimeout(updatePos,100)});
  GDML.ui={open,close:closeMenu,toggle:()=>setOpen(!opened),isOpen:()=>opened,state:{}};
  return GDML.ui;
}